### ISSUE TITLE
When we try to train the SPLUT, but got this problem

### ISSUE THREAD

**Issue by StevenTony611** [zhjy2016/SPLUT#3]
File "/share4/home/zqiang/SPLUT-main/training_testing_code/utils.py", line 347, in next
    self.lr_pngs, self.sharp_pngs, self.sr_pngs = self.shuffle_list(self.lr_pngs, self.sharp_pngs, self.sr_pngs)
ValueError: not enough values to unpack (expected 3, got 0)
===> Training start
  0%|                                                                                                                               | 0/2000000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "Train_SPLUT_S.py", line 230, in <module>
    batch_L, batch_H, batch_Stage1 = Iter_H.dequeue()
TypeError: cannot unpack non-iterable NoneType object

--------------------------------------------------------------------------------------------------------------------------
We don't know that the '/DIV2K_train_SR/*.png' includes the what type images in ./utils.py, so that cause this problem. 
Thank you!

**Comment by StevenTony611** [comment]
We try to use the DIV2K_train_HR images to replace DIV2K_train_SR and when we train the SPLUT_S model, we got this problem:

python Train_SPLUT_S.py
Found 900 images
number of model parameters: 41900
===> Training start
  0%|                                                                                                                   | 99/2000000 [00:29<142:01:17,  
AVG PSNR: Validation: 7.64958456711053
  0%|                                                                                                                  | 199/2000000 [00:59<162:58:34,  3.41it/s]SP-LUT SPLUT_S_0.001_4| Iter:   200, Sample:  6400, GPixel:6.03e-03, dT:0.2253, rT:0.0443
AVG PSNR: Validation: 7.6496941217796435
  0%|                                                                                                                  | 299/2000000 [01:30<169:25:04,  3.28it/s]AVG PSNR: Validation: 7.649609820342791
  0%|                                                                                                                  | 399/2000000 [02:01<192:30:00,  2.89it/s]SP-LUT SPLUT_S_0.001_4| Iter:   400, Sample: 12800, GPixel:4.24e-03, dT:0.2343, rT:0.0428
AVG PSNR: Validation: 7.649707565513543
  0%|                                                                                                                  | 499/2000000 [02:32<169:49:39,  3.27it/s]AVG PSNR: Validation: 7.6497197628500215
  0%|                                                                                                                  | 599/2000000 [03:02<165:44:23,  3.35it/s]SP-LUT SPLUT_S_0.001_4| Iter:   600, Sample: 19200, GPixel:3.95e-03, dT:0.2303, rT:0.0426
AVG PSNR: Validation: 7.6496701526408115
  0%|                                                                                                                  | 699/2000000 [03:33<180:22:08,  3.08it/s]AVG PSNR: Validation: 7.6497458558170965
  0%|                                                                                                                  | 799/2000000 [04:03<187:45:56,  2.96it/s]SP-LUT SPLUT_S_0.001_4| Iter:   800, Sample: 25600, GPixel:3.63e-03, dT:0.2347, rT:0.0431
AVG PSNR: Validation: 7.649865961861501
  0%|                                                                                                                  | 899/2000000 [04:34<202:33:57,  2.74it/s]AVG PSNR: Validation: 7.649724043108728
  0%|                                                                                                                  | 982/2000000 [04:58<123:10:51,  4.51it/s]
------------------------------------------------------------------------------------------------------------------------------------------
The PSNR value is so low and we don't know why causes this problem.
Thank you!

**Comment by zhjy2016** [comment]
I checked the relevant codes. This part 'DIV2K_train_SR' is not referenced in the subsequent code. You can comment out this line or download the latest version of the code. Thanks for attention!
